version: '3.9'

services:
  app:
    image: docker-nextjs-dev
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
